### notify

// @baseUrl = http://localhost:3000
@baseUrl =  'https://websocket-api-gafagjdefce5g6cr.canadaeast-01.azurewebsites.net'

POST {{baseUrl}}/api/appointments/notify 
Content-Type: application/json
Internal-WS-Api-Key: your_internal_api_key

{
    "event": "created",
    "data": {
        "appointmentId": "12345",
        "notificationType": "email"
    }
}